name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: windows-latest # 官方示例使用 windows，您也可以换回 ubuntu-latest，通常没影响
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for a more accurate analysis.
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v5 # 注意：使用了更新的 v5 版本
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # 注意：这里只留下了 SONAR_TOKEN
          # SONAR_HOST_URL 不再需要了！